language: go

go:
  - "1.13"

script:
  - go fmt ./... && [[ -z `git status -s` ]]
  - go mod vendor && go test -race -v $(go list ./... | grep -v vendor | grep -v examples) -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)